git:
  depth: false

language: node_js

node_js:
  - 12.13.1

cache:
  yarn: true
  directories:
    - "node_modules"

services:
  - docker

env:
  - CXX=g++-4.8 TZ=GMT

before_install:
  - npm install -g yarn@1.22.4

install:
  - yarn install --frozen-lockfile

jobs:
  include:
    #######################################################################
    # STAGE: RELEASE
    #######################################################################
    - stage: deploy
      if: branch = master
      name: 'Release new version'
      env:
        - GITHUB_PAGES_PATH=./dist
      script:
        - cd dist && rm -rf .git && cd ..
        - yarn add -W -D https://${GH_TOKEN}@github.com/ClubMediterranee/cmflow#v0.60.7 --frozen-lockfile
        - git checkout -- package.json
        - yarn release
stages:
  - deploy

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
