compressionLevel: mixed

enableGlobalCache: true

enableImmutableInstalls: false

nodeLinker: node-modules

supportedArchitectures:
  cpu:
    - current
    - x64
    - arm64
  os:
    - current
    - darwin
    - linux

yarnPath: .yarn/releases/yarn-4.1.1.cjs
