import './index.css'

export * from './components/animation/fade/Fade'
export * from './components/button/Button'
export * from './components/header/Header'
export * from './components/icon/Icon'
export * from './components/spinner/Spinner'
export * from './components/input-text/InputText'
export * from './components/switch/Switch'
export * from './components/tabs/Tabs'
export * from './components/footer/Footer'
