import './index.css'
// Components
export * from './components/animation/fade/Fade'
export * from './components/button/Button'
export * from './components/header/Header'
export * from './components/icon/Icon'
export * from './components/spinner/Spinner'
export * from './components/input-text/InputText'
export * from './components/input-select/InputSelect'
export * from './components/input-switch/InputSwitch'
export * from './components/input-datalist/InputDatalist'
export * from './components/switch/Switch'
export * from './components/tabs/Tabs'
export * from './components/footer/Footer'

export * from './utils/index'
