version: 2.1
orbs:
  node: circleci/node@3.0.1

commands:
  yarn-install:
    description: "Yarn install with cache optimization"
    steps:
      - node/install:
          install-yarn: true
          node-version: 12.13.1
      - node/install-packages:
          pkg-manager: yarn
      - run: node --version
      - run: npm --version
      - run: yarn --version
  cmflow-install:
    description: "Install CmFlow for the job"
    steps:
      - run:
          name: Install cmflow
          command: yarn add -W -D https://${GH_TOKEN}@github.com/ClubMediterranee/cmflow#v0.60.14 --frozen-lockfile
      - run:
          name: Reset package.json
          command: git checkout -- package.json
jobs:
  deploy:
    machine: true
    environment:
      BASE_URL: "https://clubmediterranee.github.io/swagger/latest"
      GITHUB_PAGES_PATH: "./dist"
    steps:
      - checkout
      - yarn-install
      - cmflow-install
      - run: yarn release

workflows:
  build:
    jobs:
      - deploy:
          filters:
            branches:
              only: /^master$/
          context: api
