version: 2.1
orbs:
  node: circleci/node@5.1.0

executors:
  app-executor:
    docker:
      - image: cimg/node:18.17.1
    resource_class: large

commands:
  yarn-install:
    description: "Yarn install with cache optimization"
    steps:
      - node/install-packages:
          pkg-manager: yarn

jobs:
#  lint:
#    executor: app-executor
#    steps:
#      - configure-executor
#      - workspace-restore
#      - run:
#          name: Lint
#          command: yarn lint:ci
#      - store_test_results:
#          path: reports
#      - store_artifacts:
#          path: ./reports
  test:
    executor: app-executor
    steps:
      - configure-executor
      - workspace-restore
      - run:
          name: Unit test
          command: yarn test:ci
      - store_test_results:
          path: reports
      - store_artifacts:
          path: ./reports
  deploy:
    executor: app-executor
    environment:
      BASE_URL: "https://clubmediterranee.github.io/swagger/latest"
#      GITHUB_PAGES_PATH: "./dist"
    steps:
      - checkout
      - yarn-install
      - run: yarn dlx -p @cmflow/cli cmrelease
      - run:
          name: Publish
          path: ./dist
          command: |
            git init
            git add -A
            git commit -m 'Deploy github pages'
            git push -f "https://${GH_TOKEN}@github.com/ClubMediterranee/swagger.git" master:gh-pages
workflows:
  build:
    jobs:
#      - install
#      - lint:
#          requires:
#            - install
#      - test:
#          requires:
#            - install
      - deploy:
#          requires:
#            - lint
#            - test
#          filters:
#            branches:
#              only: /^master$/
          context: api
